### PR TITLE
add shared mount point

### PR DESCRIPTION
**Pull request by QiRaining**
add shared mount point

### CODE REVIEW

**Comment by youyk** [comment]
Looks good to me.  +1

@tolbkni  how do you think？

**Comment by tolbkni** [comment]
Code looks fine. Should we improve the translations?

**Comment by youyk** [comment]
@tolbkni Can you help on the translation?

**Comment by QiRaining** [comment]
I translated by Google

**Comment by tolbkni** [comment]
Translating "shared mount point" into "共享本地存储" or "共享挂载点", which is better? @youyk

**Comment by youyk** [comment]
共享挂载点 ？

**Pull request merged**
